### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by LucasFelinto** [LucasFelinto/sandbox#1]
Eu como desenvolvedor quero criar o README para descrever o projeto.

**Comment by Patrick-Santana** [comment]
Deverás interessante,  readme com bastante conteúdo saiydgfesautyfcd\sougpiy dsa

**Comment by Patrick-Santana** [comment]
tá sabendo oq sabe:? #

**Comment by ThierryMatheus** [comment]
Que merda foi essa Lucas? Full na Disney. Nem que colocar o nome da issue no commit man!:)

**Comment by Patrick-Santana** [comment]
gastei a onda nesse commit vazio jkhdsguysafsa
