### ISSUE TITLE
Criar os Models

### ISSUE THREAD

**Issue by ThierryMatheus** [LucasFelinto/sandbox#4]
Eu **como** desenvolvedor **quero** criar os Models **para** podermos tratar os dados da aplicação.

- [ ] Configurar conexão com BD
- [ ] Criar diretório Model e seus arquivos
- [ ] Criar arquivo Model para cadastrar Aluno
- [ ] Criar arquivo Model para cadastrar Funcionário
- [ ] Criar arquivo Model para cadastrar Veículos

**Comment by lilialnas** [comment]
Se eu fosse vocês, eu criava uma issue para cada tarefa dessa. E colocava os responsáveis "assigness" nelas. ;-)
1.Configurar conexão com BD
2.Criar diretório Model e seus arquivos
3.Criar arquivo Model para cadastrar Aluno
4. Criar arquivo Model para cadastrar Funcionário
5.Criar arquivo Model para cadastrar Veículos
